export const OClade = {
  ABELISAURIA: 'Abelisauria',
  AEOLUSAURINI: 'Aeolosaurini',
  AETOSAURIFORMES: 'Aetosauriformes',
  ALBERTACERATOPSINI: 'Albertaceratopsini',
  ALLOKOTOSAURIA: 'Allokotosauria',
  ALLOSAURIA: 'Allosauria',
  ALVAREZSAURIA: 'Alvarezsauria',
  ANCHISAURIA: 'Anchisauria',
  ANKYPOLLEXIA: 'Ankylopollexia',
  ANKYLOSAURIA: 'Ankylosauria',
  APHANOSAURIA: 'Aphanosauria',
  ARCHELOSAURIA: 'Archelosauria',
  ARCHOSAURIA: 'Archosauria',
  ARCHOSAURIA_QUESTION: 'Archosauria (?)',
  ARCHOSAURIFORMES: 'Archosauriformes',
  ARCHOSAUROMORPHA: 'Archosauromorpha',
  AUSTROKRITOSAURIA: 'Austrokritosauria',
  AVEMETATARSALIA: 'Avemetatarsalia',
  AVEROSTRA: 'Averostra',
  AVETHEROPODA: 'Avetheropoda',
  AVIALAE: 'Avialae',
  BAGUALOSAURIA: 'Bagualosauria',
  BERTHASAURIDAE: 'Berthasauridae',
  BRACHYROSTRA: 'Brachyrostra',
  CAMARASAUROMORPHA: 'Camarasauromorpha',
  CARCHARODONTOSAURIA: 'Carcharodontosauria',
  CARNOSAURIA: 'Carnosauria',
  CERAPODA: 'Cerapoda',
  CERATOPSIA: 'Ceratopsia',
  CERATOPSIA_QUESTION: 'Ceratopsia (?)',
  CERATOSAURIA: 'Ceratosauria',
  CERATOSUCHOPSINI: 'Ceratosuchopsini',
  COELUROSAURIA: 'Coelurosauria',
  COELUROSAURIA_QUESTION: 'Coelurosauria (?)',
  COLOSSOSAURIA: 'Colossosauria',
  CORONOSAURIA: 'Coronosauria',
  CROCODYLOMORPHA: 'Crocodylomorpha',
  CROCOPODA: 'Crocopoda',
  CYNODONTIA: 'Cynodontia',
  DAKOSAURINA: 'Dakosaurina',
  DIAMANTINASAURIA: 'Diamantinasauria',
  DIAMANTINASAURIA_QUESTION: 'Diamantinasauria (?)',
  DINOSAURIA: 'Dinosauria',
  DINOSAURIA_QUESTION: 'Dinosauria (?)',
  DINOSAURIFORMES: 'Dinosauriformes',
  DINOSAUROMORPHA: 'Dinosauromorpha',
  DINOSAUROMORPHA_QUESTION: 'Dinosauromorpha (?)',
  DRACOHORS: 'Dracohors',
  DREPANOSAUROMORPHA: 'Drepanosauromorpha',
  DRYOMORPHA: 'Dryomorpha',
  DSUNGARIPTEROIDEA: 'Dsungaripteroidea',
  ELASMARIA: 'Elasmaria',
  ENANTIORNITHES: 'Enantiornithes',
  EUANKYLOSAURIA: 'Euankylosauria',
  EUCENTROSAURA: 'Eucentrosaura',
  EUCERATOPSIA: 'Euceratopsia',
  EUCROCOPODA: 'Eucrocopoda',
  EUDROMAEOSAURIA: 'Eudromaeosauria',
  EUHADROSAURIA: 'Euhadrosauria',
  EUMANIRAPTORA: 'Eumaniraptora',
  EURYPODA: 'Eurypoda',
  EUSAUROPODA: 'Eusauropoda',
  EUTITANOSAURIA: 'Eutitanosauria',
  EUTYRANNOSAURIA: 'Eutyrannosauria',
  FLAGELLICAUDATA: 'Flagellicaudata',
  FURILEUSAURIA: 'Furileusauria',
  GENASAURIA: 'Genasauria',
  GRAVISAURIA: 'Gravisauria',
  HADROSAURIFORMES: 'Hadrosauriformes',
  HADROSAUROMORPHA: 'Hadrosauromorpha',
  HALSZKARAPTORINAE: 'Halszkaraptorinae',
  HERRERASAURIA: 'Herrerasauria',
  IGUANODONTIA: 'Iguanodontia',
  LITHOSTROTIA: 'Lithostrotia',
  LOGNKOSAURIA: 'Lognkosauria',
  LOPHOCTRATIA: 'Lophocratia',
  MACROCHEIRIFORMES: 'Macrocheiriformes',
  MACRONARIA: 'Macronaria',
  MACRONARIA_QUESTION: 'Macronaria (?)',
  MANIRAPTORA: 'Maniraptora',
  MANIRAPTORIFORMES: 'Maniraptoriformes',
  MANIRAPTOROMORPHA: 'Maniraptoromorpha',
  MARGINOCEPHALIA: 'Marginocephalia',
  MASSOPODA: 'Massopoda',
  MEGALOSAURIA: 'Megalosauria',
  MEGARAPTORA: 'Megaraptora',
  METASUCHIA: 'Metasuchia',
  MICRORAPTORIA: 'Microraptoria',
  NANOTYRANNIDAE: 'Nanotyrannidae',
  NECERATOPSIA: 'Neoceratopsia',
  NECERATOSAURIA: 'Neoceratosauria',
  NEOCOELUROSAURIA: 'Neocoelurosauria',
  NEORNITHISCHIA: 'Neornithischia',
  NEOSAUROPODA: 'Neosauropoda',
  NEOSAUROPODA_QUESTION: 'Neosauropoda (?)',
  NEOTHEROPODA: 'Neotheropoda',
  NOTOSUCHIA: 'Notosuchia',
  ORIONIDES: 'Orionides',
  ORNITHISCHIA: 'Ornithischia',
  ORNITHISCHIA_QUESTION: 'Ornithischia (?)',
  ORNITHODIRA: 'Ornithodira',
  ORNITHOMIMOSAURIA: 'Ornithomimosauria',
  ORNITHOPODA: 'Ornithopoda',
  OVIRAPTOROSAURIA: 'Oviraptorosauria',
  PACHYCEPHALOSAURIA: 'Pachycephalosauria',
  PACHYROSTRA: 'Pachyrostra',
  PANOPLOSAURINI: 'Panoplosaurini',
  PANTYRANNOSAURIA: 'Pantyrannosauria',
  PARACROCODYLOMORPHA: 'Paracrocodylomorpha',
  PARANKYLOSAURIA: 'Parankylosauria',
  PARANKYLOSAURIA_QUESTION: 'Parankylosauria (?)',
  PARAVES: 'Paraves',
  PAREIASAURIA: 'Pareiasauria',
  PATAGONYKINAE: 'Patagonykinae',
  PENNARAPTORA: 'Pennaraptora',
  PLATEOSAURIA: 'Plateosauria',
  POPOSAUROIDEA: 'Poposauroidea',
  PSEUDOSUCHIA: 'Pseudosuchia',
  PTEROSAUROMORPHA: 'Pterosauromorpha',
  PUMILIOPAREIASAURIA: 'Pumiliopareiasauria',
  PYRODONTIA: 'Pyrodontia',
  RHABDODONTOMORPHA: 'Rhabdodontomorpha',
  RHABDODONTOMORPHA_QUESTION: 'Rhabdodontomorpha (?)',
  RINCONSAURIA: 'Rinconsauria',
  RIOJASAURIDAE: 'Riojasauridae',
  SAPHORNITHISCHIA: 'Saphornithischia',
  SAURISCHIA: 'Saurischia',
  SAUROPODA: 'Sauropoda',
  SAUROPODIFORMES: 'Sauropodiformes',
  SAUROPODOMORPHA: 'Sauropodomorpha',
  SOMPHOSPONDYLI: 'Somphospondyli',
  STEGOSAURIA: 'Stegosauria',
  STEGOSAURIA_QUESTION: 'Stegosauria (?)',
  STRUTHIOSAURINI: 'Struthiosaurini',
  STYRACOSTERNA: 'Styracosterna',
  SULCIMENTISAURIA: 'Sulcimentisauria',
  SYNAPSIDA: 'Synapsida',
  TENONTOSAURIDAE: 'Tenontosauridae',
  TERATOPHONEINI_QUESTION: 'Teratophoneini (?)',
  TETANURAE: 'Tetanurae',
  THERAPSIDA: 'Therapsida',
  THERIZINOSAURIA: 'Therizinosauria',
  THEROPODA: 'Theropoda',
  THEROPODA_QUESTION: 'Theropoda (?)',
  THYREOPHORA: 'Thyreophora',
  TITANOSAURIA: 'Titanosauria',
  TITANOSAURIFORMES: 'Titanosauriformes',
  TURIASAURIA: 'Turiasauria',
  TYRANNORAPTORA: 'Tyrannoraptora',
  UNAYSAURIDAE: 'Unaysauridae',
  ZIPHOSUCHIA: 'Ziphosuchia',
  INCERTAE_SEDIS: 'incertae sedis',
} as const;

export type Clade = (typeof OClade)[keyof typeof OClade];
